--- #YAML:1.0
name:                     Devel-Platform-Info
version:                  0.14
abstract:                 Unified framework for obtaining common platform metadata
author:
  - Barbie (BARBIE) <barbie@cpan.org>
  - Brian McCauley (NOBULL) <nobull67@gmail.com>
  - Colin Newell (NEWELL) <newellc@cpan.org>
  - Jon 'JJ' Allen (JONALLEN) <jj@jonallen.info>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                       5.006
recommends:
  Win32:                      0
  POSIX:                      0
  Test::MockObject::Extends:  0
  Test::More:                 0.70
  Test::Pod:                  1.00
  Test::Pod::Coverage:        0.08
  Test::CPAN::Meta:           0
  Test::CPAN::Meta::JSON:     0
build_requires:
  IO::File:                   0
  Test::More:                 0.70

provides:
  Devel::Platform::Info:
    file:     lib/Devel/Platform/Info.pm
    version:  0.14
  Devel::Platform::Info::BeOS:
    file:     lib/Devel/Platform/Info/BeOS.pm
    version:  0.14
  Devel::Platform::Info::BSD:
    file:     lib/Devel/Platform/Info/BSD.pm
    version:  0.14
  Devel::Platform::Info::Irix:
    file:     lib/Devel/Platform/Info/Irix.pm
    version:  0.14
  Devel::Platform::Info::Linux:
    file:     lib/Devel/Platform/Info/Linux.pm
    version:  0.14
  Devel::Platform::Info::Mac:
    file:     lib/Devel/Platform/Info/Mac.pm
    version:  0.14
  Devel::Platform::Info::SCO:
    file:     lib/Devel/Platform/Info/SCO.pm
    version:  0.14
  Devel::Platform::Info::Solaris:
    file:     lib/Devel/Platform/Info/Solaris.pm
    version:  0.14
  Devel::Platform::Info::Win32:
    file:     lib/Devel/Platform/Info/Win32.pm
    version:  0.14

no_index:
  directory:
    - t
    - examples

resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Devel-Platform-Info
  repository: git://github.com/barbie/devel-platform-info.git

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
